'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'

export default function TeacherDemoPage() {
  const [messages, setMessages] = useState<string[]>([])
  
  const sampleConversation = [
    { user: "Hi", assistant: "Hello! Welcome to your learning journey! I'm excited to help you master this material. How are you feeling today? Are you ready to tackle the challenges ahead?" },
    { user: "Yes, I'm ready!", assistant: "Wonderful! I love your enthusiasm! 📚\n\nHere are the chapters we'll be covering:\n\n**Chapter 1: Introduction to Aviation**\n**Chapter 2: Basic Aerodynamics**\n**Chapter 3: Aircraft Systems**\n**Chapter 4: Navigation Fundamentals**\n**Chapter 5: Weather Theory**\n\nWe'll be starting with Chapter 1: Introduction to Aviation. This chapter will give you a solid foundation for everything else we'll learn. Are you ready to begin?" },
    { user: "Yes, let's start", assistant: "Great! Let's dive into Chapter 1: Introduction to Aviation.\n\n**Overview:**\nAviation is the practical aspect of aeronautics, concerning the design, development, production, operation, and use of aircraft. In this chapter, we'll explore:\n\n1. **The History of Flight** - From the Wright Brothers to modern aviation\n2. **Types of Aircraft** - Fixed-wing, rotorcraft, and more\n3. **Basic Principles** - What makes an aircraft fly\n4. **Aviation Terminology** - Key terms you'll need to know\n\nLet me start by explaining the four forces of flight: Lift, Weight, Thrust, and Drag...\n\n[Teacher continues explaining...]\n\nDo you have any questions about these concepts?" },
    { user: "What's the difference between lift and thrust?", assistant: "Excellent question! Let me clarify the difference:\n\n**Lift** is the upward force that opposes gravity and keeps the aircraft in the air. It's generated by the wings as they move through the air. Think of it as the force that pulls the plane UP.\n\n**Thrust** is the forward force that propels the aircraft through the air. It's produced by the engines (jet engines or propellers). Think of it as the force that pushes the plane FORWARD.\n\nHere's a simple way to remember:\n- Lift = UP (fights gravity)\n- Thrust = FORWARD (fights drag)\n\nDid that help clarify the difference?" },
    { user: "Yes, that's clear now", assistant: "Wonderful! I'm glad that helped. You're asking great questions!\n\nNow that we've covered the main concepts of Chapter 1, I think it's time to test your understanding. I've prepared 10 questions to help reinforce what you've learned.\n\nAre you ready for a quick quiz on Chapter 1?" },
    { user: "Yes, let's do the quiz", assistant: "Perfect! Let's begin your Chapter 1 quiz. Remember, this is to help you learn, so don't worry if you're not sure about some answers. Just do your best!\n\n**Question 1:**\nWhich of the following is NOT one of the four forces of flight?\n\nA) Lift\nB) Weight\nC) Speed\nD) Drag\n\nPlease answer with just the letter (A, B, C, or D)." },
    { user: "C", assistant: "Excellent! That's correct! ✅\n\nSpeed is not one of the four forces of flight. The four forces are Lift, Weight, Thrust, and Drag. Speed is a result of these forces, not a force itself.\n\n**Question 2:**\nWhat force is responsible for moving an aircraft forward?\n\nA) Lift\nB) Thrust\nC) Weight\nD) Drag\n\nPlease answer with just the letter." },
    { user: "B", assistant: "Perfect! You're doing great! ✅\n\nThat's right - Thrust is the force that moves an aircraft forward.\n\n[Quiz continues...]\n\n**Final Results:**\nCongratulations! You scored 9 out of 10 (90%)! 🎉\n\nYou've shown an excellent understanding of Chapter 1. You're clearly ready to move on to Chapter 2: Basic Aerodynamics.\n\nWould you like to start Chapter 2 now, or would you prefer to take a break?" }
  ]
  
  const addMessage = (index: number) => {
    if (index < sampleConversation.length) {
      setMessages(prev => [...prev, `User: ${sampleConversation[index].user}`, `Teacher: ${sampleConversation[index].assistant}`])
    }
  }
  
  return (
    <div className="container mx-auto p-8 max-w-4xl">
      <h1 className="text-3xl font-bold mb-6">AI Teacher Demo</h1>
      
      <Card className="p-6 mb-6">
        <h2 className="text-xl font-semibold mb-4">How the AI Teacher Works:</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>Greets students warmly and asks if they're ready to learn</li>
          <li>Lists all available chapters when student is ready</li>
          <li>Teaches chapter content in a structured, engaging way</li>
          <li>Answers questions and checks understanding</li>
          <li>Generates quizzes with 10 questions per chapter</li>
          <li>Provides feedback on quiz answers</li>
          <li>Tracks progress and moves to next chapter after passing (80%+)</li>
          <li>Remembers where students left off for returning sessions</li>
        </ul>
      </Card>
      
      <Card className="p-6">
        <h2 className="text-xl font-semibold mb-4">Sample Conversation Flow:</h2>
        
        <div className="space-y-4 mb-6 max-h-96 overflow-y-auto">
          {messages.map((msg, i) => (
            <div key={i} className={`p-3 rounded ${msg.startsWith('User:') ? 'bg-blue-100' : 'bg-gray-100'}`}>
              <p className="whitespace-pre-wrap">{msg}</p>
            </div>
          ))}
        </div>
        
        <div className="flex gap-2 flex-wrap">
          {sampleConversation.map((_, i) => (
            <Button
              key={i}
              onClick={() => addMessage(i)}
              disabled={messages.length >= (i + 1) * 2}
              size="sm"
            >
              Step {i + 1}
            </Button>
          ))}
          <Button
            onClick={() => setMessages([])}
            variant="outline"
            size="sm"
          >
            Reset
          </Button>
        </div>
      </Card>
    </div>
  )
}
